# Generated by Django 5.0.4 on 2024-04-24 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('wanted_for', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('capture', 'Capture'), ('surveillance', 'Surveillance'), ('investigation', 'Investigation')], max_length=100)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hxnterapiapi.hunter')),
                ('wanted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hxnterapiapi.wanted')),
            ],
        ),
    ]
